services:

  apis:
    image: rhadi2005/dg-dctransfers:latest
    # image: rhadi2005/confluent-client:latest
    container_name: confluent-client
    hostname: confluent
    restart: always
    ports:
      - 8001:8000
    env_file:
      - .env
    # depends_on:
    #   - db
    volumes:
      - ./examples:/examples
      - .:/kafka-confluent

    # command: -c 'sleep infinity'
    command: ["bash", "-c", "tail -f /dev/null"]
    # command: eval 'sleep infinity'

